<b><font size=6 color='green'>ch13. N차원 배열 다루기</font>
    
* N 차원 배열 객체
* 2차원 배열은 행렬개념으로 이해 
* numpy 패키지 이용 (C 언어로 구현된 고성능 수치계산 패키지) 
* C/C++, 포트란 코드의 통합도구 

# 1절. 넘파이 패키지

In [1]:
import numpy as np 

np.__version__

'1.19.5'

## 1.1 배열 생성 함수

In [2]:
# 0부터 15앞까지 1씩 증가 하는 1차원 배열
a = np.arange(15)  #np.arange(0,15,1) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a = np.arange(15).reshape(3,5) # 1행 짜리 리스트를 3행5열 짜리로 변경
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
type(a) # a변수의 타입

numpy.ndarray

In [6]:
a.dtype # a array 내의 데이터들의 타입

dtype('int32')

In [7]:
a.dtype.name # a array 내의 데이터를 타입 내용

'int32'

In [9]:
a.itemsize # a array의 한 요소의 size : integer32 = 4byte

4

In [8]:
a.ndim # axis 수 or 차원수

2

In [10]:
a.size # 배열 내 요소의 총갯수 

15

In [11]:
a.shape # 배열의 구조 (3행5열)

(3, 5)

In [ ]:
a.shape = (5,3)
a

In [ ]:
# dtype 속성을 바꾸면 

a = np.arange(12).reshape(3,4)
a

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
a.reshape(1,12)
a

In [ ]:
a.dtype = np.int64

In [ ]:
a.dtype

In [ ]:
a # dtype을 함부로 바꾸면 데이터에 변질이 옴

In [ ]:
# dtype을 하면 전체 데이터 갯수도 변질되어, reshape도 안됨 
a.size

# 2절. 넘파이 배열 

* np.array() 함수를 이용한 다른 파이썬 구조 (벡터구조)를 넘파이 배열로 변환 
* 넘파이 배열을 생성하는 기타 함수들 : arange, ones, zeros 
* 특수 라이브러리 함수 (ex. random) 이용
* [넘파이 doc](https://numpy.org/doc/stable/index.html)

## 2.1 array() 함수로 넘파이 배열 만들기

In [ ]:
import numpy as np 

a = np.array([2,4,6.0], dtype=np.int16) # 넘파이 배열은 같은 자료형만 와야됨. 정수들 모두 실수로 자동 형변환됨
a

In [ ]:
a[0]

In [ ]:
for i in a:
    print(i, end='\t')

In [ ]:
a.dtype

In [ ]:
b = np.array([(1.5,2.3),(4,5)]) # 자동 dtype 셋팅 (float64형). shape 자동 셋팅
b

In [ ]:
a = np.array([1,2],[3,4]) # np.array() 는 항상 하나의 list만 인자값으로 받는다

In [ ]:
a = np.array([[1,2],[3,4]])
a

In [ ]:
# dtype 인수를 통해 type을 셋팅 가능 
a = np.array([1,2,3,4], dtype=np.float32).reshape(2,2)
a

In [ ]:
a.dtype

In [ ]:
for i, row in enumerate(a):
    for j, data in enumerate(row):
        print('%d행 %d열: %d'%(i,j,data))

In [ ]:
# 2차원 배열 

b = np.array([[1,2,3],[4,5,6]], dtype=np.int16)
b

In [ ]:
# 넘파이 배열 요소 조회법 1
for i, row in enumerate(b):
    for j, data in enumerate(row):
         print('%d행 %d열: %d'%(i,j,data))

In [ ]:
# 넘파이 배열 요소 조회법 2
b[0,1]

In [ ]:
# 넘파이 배열 슬라이싱
b[0,0:2]

In [ ]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

In [ ]:
# 스칼라 변수의 복제 : 그냥 변수에 대입하는 순간 이뤄짐 (객체 변수는 그렇지 않음)
a =10
b=a
a=9
print(b)

In [19]:
# numpy 배열 : 객체변수는 그냥 새로운 변수에 대입을 한다고 복사가 되지 않음.

c = np.array([[1,2,],[3,4,]])
d = np.array(c,copy=True) # 깊은 복사 
f = np.array(c,copy=False) # 얕은 복사

print('d=',d,sep='\n')
print('f=',f,sep='\n')
print('두변수의 주소:',id(c),id(d))
d[0,0] = 999
print('d=',d,sep='\n')
print('f=',f,sep='\n')

d=
[[1 2]
 [3 4]]
f=
[[1 2]
 [3 4]]
두변수의 주소: 1243279436736 1243279436896
d=
[[999   2]
 [  3   4]]
f=
[[1 2]
 [3 4]]


In [ ]:
# copy=False 이더라도 dtype이 바뀌면 깊은 복사가 일어남 
c = np.array([[1,2,],[3,4,]])
d = np.array(c,copy=False, dtype=np.int16) 

## 2.2 기본값이 있는 배열만들기 

* np.zeros(tup) : 모든 요소가 0으로 채워짐
* np.ones(tup) : 모든 요소가 1로 채워짐
* np.empty(tup) : 모든 요소가 임의의 값으로 채워짐

* 이렇게 생성된 배열은 기본 dtype=float64. 

In [ ]:
np.zeros((4,4)) # 4행 4열 짜리 0이 들어간 numpy배열 생성

In [ ]:
x = np.zeros((3,5), dtype=np.int16)
print(x)

In [ ]:
np.ones((2,5), dtype=np.int8)

In [ ]:
np.empty((2,3)) # 초기값이 메모리 상태에 따른 임의의 값 

## 2.3 연속된 값을 갖는 배열 만들기 

* np.arange(from, to, by, dtype=None) : from 부터 to-1까지 by씩 건너뛴 값을 목록으로 N차원 배열을 만듬. from=0, by=1 디폴트값
* np.linspace(from, to, num) : from 부터 to까지 num개의 숫자들을 N차원 배열로 만듬
* np.random.normal(평균,표준편차, 갯수) : 평균이0이고, 표준편차가 1인 100개의 난수 생성
* np.random.random(rup): 0~1 사이의 난수발생

In [ ]:
np.arange(10,30,5, dtype=np.float32)

In [ ]:
np.arange(0,2,0.3)

In [ ]:
np.linspace(1,10,10).reshape(5,2)

In [ ]:
# 많은 수의 점들을 생성할 때 유용 : linspace

from numpy import pi 
import matplotlib.pyplot as plt
x = np.linspace(0,2*pi,100)
f = np.sin(x)

plt.scatter(x,f)
plt.title('sin graph by x values')
plt.xlabel('x')
plt.ylabel('y')
plt.show()


In [ ]:
np.random.seed(12)
x = np.random.normal(0,1,100)
plt.hist(x)
plt.title('histogram of random distribution')
plt.xlabel('x')
plt.show()

## 2.4 배열의 차원변경하기 

In [ ]:
np.random.seed(123)
t = np.random.random((2,3)) # 0~1인 실수 난수 발생

In [ ]:
a = np.floor(t*10)
a

In [ ]:
a.shape

In [ ]:
# 차원이 풀린 배열을 반환 -> a 에 다시 대입해주지 않으면 a 는 변함이 없음
a.ravel()

In [ ]:
## 대부분 실행 후 콘솔창에 결과물이 나오는건 원래 a 객체에 변화가 없음
## 결과물이 콘솔창에 안 뿌려지는 것은 a 객체에 변화가 적용됨
a.reshape(3,2)

In [ ]:
# a 행렬을 전치함 
a.T
a.transpose()

In [ ]:
a.reshape(3,-1) # -1로 주어지면 해당 차원의 크기가 자동계산 됨

In [ ]:
a.reshape(-1,2) # -1은 자동적으로 계산됨 (a는 그대로)

In [ ]:
# a.shape = (1,6)

a.resize((1,6)) # a에 변경된 것이 적용됨 
a

In [ ]:
a.resize(-1,2) # reshape() 에서만 - 부호 사용가능 

In [ ]:
# 가장 많이 쓰는 방식임 

a = a.reshape(2,3)

In [ ]:
# 로또 번호 6개 (1~45)를 구해서 sort 하여 1차원 배열에 넣고 출력하기

while True:
    lotto = np.floor(np.random.random(6)*45)+1
    lotto = [int(x) for x in lotto]
    lotto = np.sort(lotto)
    lotto2 = set(lotto)
    
    if len(lotto) == len(lotto2):
        print(lotto2)
        break

In [ ]:
# 배열이 너무 커서 인쇄할 수 없는 경우 

print(np.arange(10000))

In [ ]:
# 배열이 너무 커서 인쇄할수 없는 경우는 자동으로 건너뛰고 모서리만 출력
# 이동작을 비활성화하고 넘파이 배열을 전체가 출력되도록 할려면 
# 인쇄 옵션을 변경. threshold 큰 값으로 조정

np.set_printoptions(threshold=10000)
print(np.arange(10000))

In [ ]:
np.set_printoptions(threshold=np.inf) # 무제한으로 다 보기
print(np.arange(10000))

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize) # system 최고 threshold로 보기
print(np.arange(10000))

## 2.6 기본 연산동작

### 1) 배열의 요소별 연산

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

In [ ]:
## 요소별 연산의 예시
a+b
a-b
a*b
a<35

### 2) 행렬의 곱 (@) cf. * (요소별 곱) 

In [ ]:
A = np.array([[1,0],
             [0,1]])

In [ ]:
B = np.array([[2,0],
              [3,4]])

In [ ]:
A,B

In [ ]:
print('요소별 곱 A*B = ', A*B, sep='\n')

### 3) 복합대입 연산자 사용 (+=,==,*=,....)

In [ ]:
a = np.ones((2,3),dtype=int)
a

In [ ]:
b = np.random.random((2,3)) # 2차원 2행3열 짜리 배열, dtype=float64
b

In [ ]:
a +=3
a

In [ ]:
b +=a
b

In [ ]:
a+=b # b 가 dtype이 float64 이어서 a+b가 float64로 강제 형변환이 일어남

In [ ]:
a = np.ones(3, dtype=np.int16)
b = np.linspace(0, np.pi,3)
print(a)
print(b)

In [ ]:
c = a+b
print(c.dtype)

In [ ]:
c = a +b*1j
c.dtype

### 4) 배열요소별 집계: 배열요소 전체의 sum, min... 

In [1]:
a = np.array([[2,2,2,4],
             [4,3,2,1]])
a

array([[2, 2, 2, 4],
       [4, 3, 2, 1]])

In [2]:
print('전체 합:',a.sum())
print('전체 평균:', a.mean())
print('전체 최소값:', a.min())
print('전체 최대값:', a.max())
print('전체 분산:', a.var())

전체 합: 20
전체 평균: 2.5
전체 최소값: 1
전체 최대값: 4
전체 분산: 1.0


### 5)배열 축별 집계: 행별 sum,min, ... 열별 sum, min, .... 

In [3]:
a = np.array([[2,2,2,4],
              [4,3,2,1]])
a

array([[2, 2, 2, 4],
       [4, 3, 2, 1]])

In [4]:
print('a 배열의 행별 합(결과는 2열): ', a.sum(axis=1)) # 행별 합

a 배열의 행별 합(결과는 2열):  [10 10]


In [5]:
print('a 배열의 열별 합(결과는 2열): ', a.sum(axis=0)) # 열별 합

a 배열의 열별 합(결과는 2열):  [6 5 4 5]


In [6]:
print('a배열의 행별 최소값:', a.min(axis=1))
print('a배열의 열별 최소값:', a.min(axis=0))

a배열의 행별 최소값: [2 1]
a배열의 열별 최소값: [2 2 2 1]


In [ ]:
'''
array([[2,2,2,4],
      [4,3,2,1]])

'''
print('a배열의 행별 최대 값이 있는 index:',a.argmax(axis=1))

In [ ]:
# 누적합 

print(a)
print(a.cumsum(axis=1)) # 행별로 누적합 

In [ ]:
b = np.arange(24).reshape(2,3,4) # 2면 3행 4열짜리 3차원 배열
b

In [ ]:
print('전체 요소의 합: ',b.sum())
print('전체 요소의 표준편차: ',np.sqrt(b.var()))

In [ ]:
b.sum(axis=0) # 면은 뺴고, 같은 행, 같은 열끼리 sum 
# 0면의 0행 0열 + 0면의 0열 1열 +..... 

## 2.7 그외 함수들 (난수 발생: 1차원 배열, 요소연산)

In [ ]:
a = np.arange(3)
a = np.sqrt(a)
a

import math 

# math.sqrt(a) -> 에러 발생. math.sqrt()는 스칼라 값 만을 인자값으로 받음 

In [ ]:
a = np.arange(3)
b = np.array([10,11,12])
a+b

In [ ]:
np.add(a,b)

In [ ]:
np.random.rand(5) # 0~1 미만의 난수 5개 발생 (균일 분포에서 난수)

In [ ]:
np.random.randn(5) # 평균이 0이고 표준편차가 1인 정규분포에서 난수 5개 발생

In [ ]:
np.random.randint(5) # 0~5미만의 정수 난수 발생

In [ ]:
# rand() 가 균일 분포에서 난수 발생 확인 
import matplotlib.pyplot as plt 

x = np.random.rand(1000) # 1000개의 균일 분포 생성 
plt.hist(x, bins=100)
plt.xlabel('x')
plt.title('histogram of uniform dist')
plt.show()

In [ ]:
# randn() 가 표준 정규 분포에서 난수 발생 확인 
import matplotlib.pyplot as plt 

x = np.random.randn(1000000) # 1000개의 균일 분포 생성 
plt.hist(x, bins=1000)
plt.xlabel('x')
plt.title('histogram of normal dist')
plt.show()

In [ ]:
# 메모리 사용량과 속도 특정 (메모리 프로파일러)를 로드 하고 임의의 데이터 생성 후 + np.add 비교
#  아나콘다 프롬포트에서 memroy_profiler 패키지 install

A = np.random.randn(100000000)
B = np.random.randn(100000000)
C  = np.random.randn(100000000)

In [ ]:
# %%time : 셀을 실행할 때 소요시간 출력 -> 주석이 있는 셀과 같이 쓰면 실행안됨
# %memit: 메모리 사용량 출력 
%load_ext memory_profiler

In [ ]:
%%time
%memit G = A*B+C
print(G)

In [ ]:
%%time
%memit T = A*B; G = T+C; del T
print(G)

In [ ]:
%%time
%memit G = A*B; G +=C
print(G)

In [ ]:
# np.add() 경우 배열 요소별 연산을 할 경우 메모리 절약 

In [ ]:
%%time
%memit G = A*B; np.add(G,C,G)
print(G)

## 2.8 브로드 캐스팅

* 행수 또는 열수가 어느 정도 일치해야 브로드캐스팅이 이뤄짐

In [ ]:
# 1차원 배열인 경우 

a = np.array([1,2,3])
b = 10

np.add(a,b)

In [ ]:
# 2차원 배열인 경우 

a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])

b = np.array([5,5,5])
np.multiply(a,b)

In [ ]:
c = np.array([5,1])
np.multiply(a,b)

In [ ]:
a = np.array([0,10,20,30])  # 1행 4열

In [20]:
#newaxis 연산자 이용하여 배열에 새로운 축을 추가해서 2차원인 4행 1열로 변환 
x = a[:,np.newaxis]
print(x,end='\n\n') # 4행1열
b = np.array([1,2,3]) # 1행 3열
print(b)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]

[1 2 3]


In [21]:
a = np.array( [1,2,3] )

print(a[:, np.newaxis])

[[1]
 [2]
 [3]]


In [ ]:
result = np.add(x,b)
result

# 3절. 배열 합치기/분할하기

In [7]:
a = np.arange(10) *3
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

## 3.1 인덱싱과 슬라이싱

In [8]:
# 1) 인덱싱 

a[2]

6

In [9]:
a[-1]

27

In [10]:
# 2) 슬라이싱

a[0:100:2] # 슬라이싱의 경우 벗어난 인덱스 값이어도 가능

array([ 0,  6, 12, 18, 24])

In [11]:
# 인덱스로 값 할당 

a[:6:2] = -99
a

array([-99,   3, -99,   9, -99,  15,  18,  21,  24,  27])

In [12]:
# 3) 다차원 배열의 인덱싱 & 슬라이싱

a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a[2,2]

In [13]:
# 마지막 열들만 추출 : 1차원 array 반환 = list 
a[:,-1]

array([ 3,  7, 11, 15, 19])

In [14]:
# 0~2행 까지의 마지막 열들만 

a[0:3,-1]

array([ 3,  7, 11])

In [ ]:
# 모든행의 마지막 열을 제외한 데이터 추출 : 처음 부터 끝까지 마지막 열 전까지 

a[:,:-1]

In [ ]:
# 0~4행만 추출 

a[0:5,:] # 열을 생략하면 모든 열 

In [ ]:
a[0:3]

In [ ]:
a[0:3,...] ## ... = 누락된 인덱스 전체

In [ ]:
a[..., -1] ## 전체행 마지막 열

In [ ]:
# 모든 행에 마지막열, 마지막 전열 추출 

X = a[...,-1:-3:-1]
X

In [22]:
X = a[...,-2::]
X

array([2, 3])

## 3.2 두 배열을 쌓아 합치기

**vstack(tup) : 아래에 추가하는 방식으로 쌓아 함침 (= R의 rbind())**

**hstack(tup) : 옆으로 추가하는 방식으로 합침 (=  R의 cbind())**

**dstack(tup) : 마지막 축(열)을 쌓아 합침. 0열들끼리 쌓고, 1열끼리 쌓고**

**column_stack(tup): 1차원 배열을 열 단위로 배열하여 2차원 배열로 합침**

**row_stack(tup):  column_stack(tup)과 반대로 row단위로 합침**

**stack(tup, axis=0): axis값에 따라 열 또는 행별로 배열을 합침**

<b>r_\[a,b,c\], c_\[a,b,c\]: R의 rbind(), cbind()와 유사 </b>

In [15]:
c = np.arange(24).reshape(2,3,4) # 2면 3행 4열
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
a,b = c[0], c[1]
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
np.hstack((a,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [19]:
np.dstack((a,b)) # 열들끼리 쌓아서 면을 생성 

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [20]:
# column_stack(a,b,c): a,b,c 각 리스트를 열별로 합쳐서 하나의 array를 만듬
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

np.column_stack((a,b,c))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
# column_stack() 안쓰고 합치기
x = a[:,np.newaxis]
y = b[:,np.newaxis]
z = c[:,np.newaxis]

np.hstack((x,y,z))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [22]:
np.row_stack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [23]:
# np.stack(tup, axis): axis=0이면 첫번째 차원 으로 합침, axis=1이면 두번째 차원으로 합침

a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)

np.stack((a,b),axis=0) # 각 행렬 당 하나의 면을 이룸

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
np.stack((a,b),axis=1) # 각 행끼리 합쳐서 면을 이룸

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [25]:
np.stack((a,b),axis=2) # 각 열끼리 합쳐서 면을 이룸

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [26]:
a = np.arange(12)
b = np.arange(12,24)
c = np.arange(24,36)

In [27]:
np.r_[[a],[b],[c]] #np.r_[a,b,c] : 이렇게 하면 그냥 한줄안에 다 쌓아버림

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [28]:
np.c_[a,b,c]

array([[ 0, 12, 24],
       [ 1, 13, 25],
       [ 2, 14, 26],
       [ 3, 15, 27],
       [ 4, 16, 28],
       [ 5, 17, 29],
       [ 6, 18, 30],
       [ 7, 19, 31],
       [ 8, 20, 32],
       [ 9, 21, 33],
       [10, 22, 34],
       [11, 23, 35]])

In [1]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 3.3 배열 분리하기

**vsplit(array, 분할기준 인덱스 or 분할갯수): 첫번째 축(2차원의 경우 가로축)을 따라 분할**

**hsplit(array, 분할기준 인덱스 or 분할갯수): 두번째 축(2차원의 경우 세로축)을 따라 분할**

**dsplit(array, 분할기준 인덱스 or 분할갯수): 3번째 축(3차원의 경우 면)을 따라 분할**

    <p>분할기준 인덱스 : 리스트 값으로 입력. [3,6] -> 0~3, 3~6, 6~ 번째 데이터들로 분리.</p>
    <p>분할 갯수로 분리: 정수값 n 을 입력받음 -> n개의 섹션으로 나눔</p>
    
**split(array, 분할기준 인덱스 or 분할갯수, axis=?): axis=0이면 vsplit, axis=1이면 hsplit, axis=2이면 dsplit**

**array_split(array, 분할기준 인덱스 or 분할갯수, axis=?): split과 동일하지만, section 수가 정확히 동일하게 갯수가 분할 되지 않아도 섹션 수로 split 가능** 

In [32]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a_vsplit = np.split(a,3) # 세로 축을 따라 3개의 array으로 분리 
a_vsplit # 첫번째 축을 분할한다 (3차원일 경우 = 면을 기준으로 분리)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [34]:
np.vsplit(a,[2]) ## 2번째 리스트

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [4]:
np.vsplit(a,[1,2]) # 1,2번 인덱스 기준으로 3개 배열로 분할 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [35]:
np.hsplit(a,2) # 세로로 2개로 나눔

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [36]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
np.vsplit(b,2) # 첫번째 축을 분할 

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [38]:
np.hsplit(b,3) 

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [39]:
np.hsplit(b,3)[0].shape

(2, 1, 4)

In [40]:
np.dsplit(b,2) ## 3번째 축(열) 기준으로 2개 섹션으로 나눔

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [41]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
np.split(a,2,axis=0) # np.vsplit()과 동일

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [43]:
np.split(a,2,axis=1) # np.hsplit()과 동일

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [44]:
np.array_split(a,3,axis=1) # 딱 맞아 떨어지지 않는 정수로도 섹션 갯수로 분할 가능

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6],
        [14, 15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]