# ch13. numpy 배열 연습

## 0. iris 데이터 로드 하기

In [3]:
import numpy as np 
from sklearn import datasets 
iris = datasets.load_iris()
iris_data = iris.data

iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## 1. 각 변수 별 평균 출력하기

In [4]:
iris_data.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

## 2. 처음 다섯개 행만 출력 하기

In [5]:
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## 3. 처음 다섯개 행에서 마지막 열을 제외한 나머지 열을 출력 

In [13]:
iris_data[:5,:-1]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

## 4.처음 다섯개 행에서 마지막 열만 출력

In [15]:
iris_data[:5,-1]

array([0.2, 0.2, 0.2, 0.2, 0.2])

## 5. 3번 배열과 4번배열을 본래 모양이 되도록 합치기

In [17]:
np.hstack((iris_data[:5,:-1],iris_data[:5,-1][:,np.newaxis]))

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## 6. 처음 다섯개 행을 이용해서 열별로 평균보다 큰 값들만 출력

In [19]:
iris_data[:5].mean(axis=0)

array([4.86, 3.28, 1.4 , 0.2 ])

In [20]:
iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [25]:
indeces = iris_data[:5].mean(axis=0) > iris_data[:5]

In [26]:
iris_data[:5][indeces]

array([3. , 4.7, 3.2, 1.3, 4.6, 3.1])

## 객관식 풀이형

### 1. print(a.sum(0))의 결과는?

In [28]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
print(a.sum(0))

[12 15 18 21]


### 2. a 배열의 차원을 바꿀수 있는 방법은?

In [31]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 4., 9., 1.],
       [1., 4., 5., 6.],
       [5., 7., 2., 5.]])

In [32]:
a.shape

(3, 4)

In [33]:
a.ravel()

array([2., 4., 9., 1., 1., 4., 5., 6., 5., 7., 2., 5.])

In [34]:
a.reshape(6,2)

array([[2., 4.],
       [9., 1.],
       [1., 4.],
       [5., 6.],
       [5., 7.],
       [2., 5.]])

In [35]:
a.resize((2,6))

In [36]:
a.T(4,3) ## 전치 행렬을 잘못 구한 예 

TypeError: 'numpy.ndarray' object is not callable

### 3번. 다음 배열에서 첫번째 행과 두번 쨰 행만 추출하는 코드는?

In [37]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 4번. 다음 코드의 실행결과는?

In [39]:
a = np.array([1,2,3,4,5])
a[[1,3,4]] = 0 
a

array([1, 0, 3, 0, 0])

### 5번. 두 배열 a와 b를 열 단위로 쌓기 위한 코드는?

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [42]:
np.c_[a,b]

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])